name: Deploy (API + Web)

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore
        run: dotnet restore

      - name: Publish API
        run: dotnet publish ./LumiumPortal.API/LumiumPortal.API.csproj -c Release -o out-api

      - name: Publish Web
        run: dotnet publish ./LumiumPortal.Web/LumiumPortal.Web.csproj -c Release -o out-web

      - name: Stop services
        run: |
          sudo systemctl stop lumium-api
          sudo systemctl stop lumium-web

      - name: Copy API
        run: sudo cp -r ./out-api/. /var/www/lumium-api/app/

      - name: Copy Web
        run: sudo cp -r ./out-web/. /var/www/lumium-web/app/

      - name: Start services
        run: |
          sudo systemctl start lumium-api
          sudo systemctl start lumium-web